name: Build ZMK User Config

on:
  push:
    tags:
      - '**'  # Triggers on any tag push
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
